Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64" # Ubuntu 22.04 LTS

  # Sync only binaries and scripts instead of the whole project
  config.vm.synced_folder "../../build", "/opt/vpn/bin"
  config.vm.synced_folder "../scripts", "/opt/vpn/scripts"

  # Forward WireGuard port
  # config.vm.network "forwarded_port", guest: 51820, host: 51820, protocol: "udp"
  
  # Create private network
  config.vm.network "private_network", type: "dhcp"

  # Run the startup script
  config.vm.provision "shell" do |s|
    s.path = "../scripts/startup.sh"
    s.privileged = true
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end
end
